[build]
  publish = ".next"
  command = "npm ci --legacy-peer-deps || npm install --legacy-peer-deps --force; npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"

# Environment variables for production
# Add these in Netlify dashboard under Site settings > Environment variables
# NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=your_project_id
# NEXT_PUBLIC_ALCHEMY_API_KEY=your_alchemy_key
# NEXT_PUBLIC_SOMNIA_RPC_URL=https://somnia-rpc-url
# GEMINI_API_KEY=your_gemini_api_key (server-side only)
