[build]
  publish = ".next"
  command = "rm -f package-lock.json && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"
  PNPM_FLAGS = "--no-frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"

# Environment variables for production
# Add these in Netlify dashboard under Site settings > Environment variables
# NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=your_project_id
# NEXT_PUBLIC_ALCHEMY_API_KEY=your_alchemy_key
# NEXT_PUBLIC_SOMNIA_RPC_URL=https://somnia-rpc-url
# GEMINI_API_KEY=your_gemini_api_key (server-side only)
